### ISSUE TITLE
mounter is missing GetSafeFormatAndMount method

### ISSUE THREAD

**Issue by RomanBednar** [IBM/ibm-csi-common#76]
When moving the resize code from driver to this library the dependency was not vendored in https://github.com/IBM/ibm-csi-common/pull/70

This causes failures in csi driver when I bump to latest ibm-csi-common:

```
$ make test
go test -v -race ./cmd/... ./pkg/...
# github.com/IBM/ibm-csi-common/pkg/mountmanager
vendor/github.com/IBM/ibm-csi-common/pkg/mountmanager/fake-safe-mounter.go:109:23: r.NeedResize undefined (type *mount.ResizeFs has no field or method NeedResize)
vendor/github.com/IBM/ibm-csi-common/pkg/mountmanager/safe-mounter.go:48:9: cannot use &NodeMounter{…} (value of type *NodeMounter) as type Mounter in return statement:
        *NodeMounter does not implement Mounter (missing GetSafeFormatAndMount method)

```

When this is fixed all dependencies in the driver should be obtained transitively via ibm-csi-common.

**Comment by RomanBednar** [comment]
/assign @ambiknai 

I believe `go mod tidy && go mod vendor` should clean this up, but we'll need a new release.

**Comment by ambiknai** [comment]
@RomanBednar  We don't maintain vendor folder in this repository.   Once you update go.mod file in [driver](https://github.com/kubernetes-sigs/ibm-vpc-block-csi-driver)code, could you please do go mod tidy   && go mod vendor. It should pick up the changes.

**Comment by RomanBednar** [comment]
@ambiknai I see...and my previous assumption is not correct. However the missing method is still causing problems. For example when running `make verify` in unsupported OS. For example on macOS this will use code from `mount_unsupported.go` which is missing the method.

```
13:18 $ make verify 
echo "Verifying and linting files ..."
Verifying and linting files ...
./hack/verify-all.sh
Verifying gofmt
No issue found
Verifying govet
# github.com/IBM/ibm-csi-common/pkg/mountmanager
vendor/github.com/IBM/ibm-csi-common/pkg/mountmanager/safe-mounter.go:48:9: cannot use &NodeMounter{…} (value of type *NodeMounter) as type Mounter in return statement:
        *NodeMounter does not implement Mounter (missing GetSafeFormatAndMount method)
make: *** [verify] Error 2
✘-2 ~/git/ibm-vpc-block-csi-driver [snapshot-resize ↑·6|⚑ 1] 
```

When I add the method it works fine:

```
13:18 $ make verify 
echo "Verifying and linting files ..."
Verifying and linting files ...
./hack/verify-all.sh
Verifying gofmt
No issue found
Verifying govet
Done
Verifying golint
Congratulations! Lint check completed for all Go source files.
Repo uses 'go mod'.
+ env GO111MODULE=on go mod tidy
+ env GO111MODULE=on go mod vendor
Go dependencies and vendor directory up-to-date.
echo "Congratulations! All Go source files have been linted."
Congratulations! All Go source files have been linted.
```

**Comment by RomanBednar** [comment]
Right, we're not keeping the old method. Fixed it in the [PR](https://github.com/IBM/ibm-csi-common/pull/77/files#diff-8320fcdb313814935bc0b5a4e47e10111d2886df822ae256caf8df9d8f9ac8f7L47).
